### ISSUE TITLE
Possible issue with README.md

### ISSUE THREAD

**Issue by s-worden** [carbonblack/cb-taxii-connector#17]
Hello,
I might just be doing it wrong, but it appears some of the sample commands in the README.md are not correct.

Line 151: /usr/share/cb/integrations/cbtaxii/cbtaxii -c /etc/cb/integrations/cbtaxii/cbtaxii.conf
  This does work for me after the latest upgrade, I get /usr/share/cb/integrations/cbtaxii/cb-taxii-connector: command not found. If instead, I use /usr/share/cb/integrations/cbtaxii/bin/cb-taxii-connector -c /etc/cb/integrations/cbtaxii/cbtaxii.conf then it works.

Line 166: /usr/share/cb/integrations/cbtaxii/cbtaxii -c /etc/cb/integrations/cbtaxii/cbtaxii.conf -l
  Same issue as above, but if I try the alternative path get unrecognized argumets: -l.

Line 183: /usr/share/cb/integrations/cbtaxii/cbtaxii -c /etc/cb/integrations/cbtaxii/cbtaxii.conf --export
  Same as the first issue.

If my change in pathing is correct, I would be happy to try and make the necessary changes.

Regards

**Comment by askthedragon** [comment]
The next release will solve these issues.  Thank you for reporting this.
